version: '3.6'

services:
  database:
    image: mariadb:10.7.1-focal
    ports:
      - '${DB_PORT:-3306}:3306'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - 'MYSQL_DATABASE=${DB_MYSQL_SCHEMA}'
      - 'MYSQL_USER=${DB_MYSQL_USERNAME}'
      - 'MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_MYSQL_PASSWORD}'
